name: Release

on:
  push:
    tags: 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
